<!Doctype html>
<html>
<body style="color: #333;">
  <div style="width:670px; margin:15 auto; border:1px solid #CCC;">
      <table style="width:100%; padding:10px; border-collapse:collapse;">
          <tr>
            <td colspan="3" style="text-align: center; font-weight: 14px;">
              <?= $this->config->item('app_company_name'); ?>             
            </td>
          </tr>
          <tr><td style="text-align: center; font-size:11px;" colspan="3"><strong>Voucher # <?= $voucherInfo->voucher_no; ?></strong></td></tr>
      </table>
    <div style="width:100%;">
      <table style="width:100%; padding:10px; border-collapse:collapse;">
          <?php
           if(!empty($voucherInfo)): ?>
            <tr>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px; width:80px;'>Date</td>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px;'><?= $voucherInfo->voucher_date; ?></td>
            </tr>
            <tr>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px; width:80px;'>Caption</td>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px;'><?= $voucherInfo->voucher_caption; ?></td>
            </tr>
            <tr>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px; width:80px;'>Reg. Branch</td>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px;'><?= $voucherInfo->reg_branch_name; ?></td>
            </tr>
            <tr>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px; width:80px;'>Branch</td>
                <td style='padding-top:10px; padding-bottom:10px; font-size:10px;'><?= $voucherInfo->branch_name; ?></td>
            </tr>
          <?php endif; ?>
      </table>

       <table style="width:90%; padding:10px; border-collapse:collapse;">
          <thead>
            <tr>
              <th style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: center;'>SN</th>
              <th style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: center;'>Transaction Head</th>
              <th style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: center;'>Debit</th>
              <th style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: center;'>Credit</th>
            </tr>
          </thead>
          <tbody>
              <?php $i=1; foreach ($tranList as $v): ?>
              <tr>
                  <td style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: center;'><?php echo $i++ ?></td>
                  <td style='padding-top:10px; padding-bottom:10px; font-size:10px;'><?php echo $v->head_name, ' / ', $v->sub_head_name, ' / ', $v->tran_head_name ?></td>
                  <td style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: right;'><?php echo $v->debit ?></td>
                  <td style='padding-top:10px; padding-bottom:10px; font-size:10px; text-align: right;'><?php echo $v->credit ?></td>
              </tr>
              <?php endforeach; ?>
          </tbody>
    </table>
    </div>

  </div>
    <span style="text-align:right;font-size:10px; margin-left:15px;">
      Date: <?= date("d M, Y / h:m:s:A")?> | Generated by <?= auth('name'); ?>
    </span>
</body>
</html>
